Repository globus-demo/globus-app, pull requests merged in 2021-04, with the labels that each got.

#10 Edit authorization page and add register page with some logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/technopolis_education/globusapp/MainAuthorization.kt
  app/src/main/java/com/technopolis_education/globusapp/MainRegister.kt
  app/src/main/res/layout-v28/authorization_main.xml
  app/src/main/res/layout/authorization_main.xml
  app/src/main/res/layout/register_main.xml
  app/src/main/res/values/strings.xml
Labels: backend, enhancement, frontend

#14 Add fragments (all working)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/technopolis_education/globusapp/FeedActivity.kt
  app/src/main/java/com/technopolis_education/globusapp/MainActivity.kt
  app/src/main/java/com/technopolis_education/globusapp/MainAuthorization.kt
  app/src/main/java/com/technopolis_education/globusapp/MainMessenger.kt
  app/src/main/java/com/technopolis_education/globusapp/MainRegister.kt
  app/src/main/java/com/technopolis_education/globusapp/ProfileActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottom_navigation_bar.xml
  app/src/main/res/layout/feed_activity.xml
  app/src/main/res/layout/messenger_main.xml
  app/src/main/res/layout/profile_page.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle
Labels: backend, enhancement, frontend

#16 Добавлена иконка глобуса в страницу профиля, изменен цвет подложки
  app/src/main/globus-playstore.png
  app/src/main/res/drawable/circle_glob.xml
  app/src/main/res/drawable/glob_int.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/authorization_main.xml
  app/src/main/res/layout/feed_activity.xml
  app/src/main/res/layout/messenger_main.xml
  app/src/main/res/layout/profile_page.xml
  app/src/main/res/mipmap-anydpi-v26/globus.xml
  app/src/main/res/mipmap-anydpi-v26/globus_round.xml
  app/src/main/res/mipmap-hdpi/globus.png
  app/src/main/res/mipmap-hdpi/globus_foreground.png
  app/src/main/res/mipmap-hdpi/globus_round.png
  app/src/main/res/mipmap-mdpi/globus.png
  app/src/main/res/mipmap-mdpi/globus_foreground.png
  app/src/main/res/mipmap-mdpi/globus_round.png
  app/src/main/res/mipmap-xhdpi/globus.png
  app/src/main/res/mipmap-xhdpi/globus_foreground.png
  app/src/main/res/mipmap-xhdpi/globus_round.png
  app/src/main/res/mipmap-xxhdpi/globus.png
  app/src/main/res/mipmap-xxhdpi/globus_foreground.png
  app/src/main/res/mipmap-xxhdpi/globus_round.png
  app/src/main/res/mipmap-xxxhdpi/globus.png
  app/src/main/res/mipmap-xxxhdpi/globus_foreground.png
  app/src/main/res/mipmap-xxxhdpi/globus_round.png
  app/src/main/res/values/colors.xml
  build.gradle
Labels: frontend

#15 Implemented simple room db and feed recycle view
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/technopolis_education/globusapp/FeedActivity.kt
  app/src/main/java/com/technopolis_education/globusapp/MainActivity.kt
  app/src/main/java/com/technopolis_education/globusapp/PostsRecyclerAdapter.kt
  app/src/main/java/com/technopolis_education/globusapp/db/messages/Message.kt
  app/src/main/java/com/technopolis_education/globusapp/db/posts/Post.kt
  app/src/main/java/com/technopolis_education/globusapp/db/posts/PostDao.kt
  app/src/main/java/com/technopolis_education/globusapp/db/posts/PostDatabase.kt
  app/src/main/java/com/technopolis_education/globusapp/db/posts/PostRepository.kt
  app/src/main/java/com/technopolis_education/globusapp/db/posts/PostViewModel.kt
  app/src/main/java/com/technopolis_education/globusapp/db/users/User.kt
  app/src/main/java/com/technopolis_education/globusapp/db/users/UserDao.kt
  app/src/main/java/com/technopolis_education/globusapp/db/users/UsersDatabase.kt
  app/src/main/res/drawable/myrect.xml
  app/src/main/res/layout/feed_post.xml
  build.gradle
Labels: backend, documentation, enhancement, help wanted
